"""Generated vocabulary term references.

Source: ``dirpluck_docs.vocabulary.canonical``.

Each ``TERM_N`` proxy exposes the human-readable term and definition in
its docstring.  Pass this module to ``@vocabulary(...)`` and use the proxies
with ``vocabulary_refs``.  Canonical vocabulary identity is retained internally.

This file is generated by shikumi-devdoc.  Do not edit it manually.
"""

from __future__ import annotations

import dirpluck_docs.vocabulary.canonical as _VOCABULARY_SOURCE

_VOCABULARY = _VOCABULARY_SOURCE.VOCABULARY
__shikumi_devdoc_vocabulary_source__ = _VOCABULARY_SOURCE


__all__ = [
    "TERM_1",
    "TERM_2",
    "TERM_3",
    "TERM_16",
    "TERM_4",
    "TERM_5",
    "TERM_6",
    "TERM_7",
    "TERM_8",
    "TERM_9",
    "TERM_10",
    "TERM_12",
    "TERM_13",
    "TERM_14",
    "TERM_15",
]


class TERM_1:
    r"""dirpluck

宣言された抽出意図に従って source からファイルを選び、ZIP アーカイブを作成する CLI ツール。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_1

class TERM_2:
    r"""設定ファイル

dirpluck の抽出意図を TOML で記述した文書。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_2

class TERM_3:
    r"""対象

実行時に選ぶ source directory へ共通の選択規則を適用するための source 定義。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_3

class TERM_16:
    r"""ターゲットロケーション

実行時に対象を探す基準として名前を付けたディレクトリ。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_16

class TERM_4:
    r"""ケース

base とは別の抽出 variation として名前を付けた選択定義。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_4

class TERM_5:
    r"""コンパニオン

設定ファイルに source directory を固定し、同じ抽出意図へ付随させる source 定義。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_5

class TERM_6:
    r"""対象ディレクトリ

対象またはコンパニオンに対応し、実際にファイルを抽出するディレクトリ。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_6

class TERM_7:
    r"""抽出

source directory からアーカイブへ含めるファイルを選択規則に従って確定する処理。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_7

class TERM_8:
    r"""アーカイブ

dirpluck が抽出結果から生成する ZIP 成果物。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_8

class TERM_9:
    r"""出力定義

生成するアーカイブの出力先と命名方針を記述する設定。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_9

class TERM_10:
    r"""アーカイブREADME

アーカイブのルートに生成され、含まれる内容を示す索引文書。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_10

class TERM_12:
    r"""共有パターン

選択定義から参照して再利用する、名前付きの include または exclude パターン集合。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_12

class TERM_13:
    r"""設定インポート

別の設定ファイルを内側の layer として取り込み、定義を組み合わせる仕組み。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_13

class TERM_14:
    r"""ルート設定ファイル

1回の dirpluck 実行を開始する最外側の設定ファイル。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_14

class TERM_15:
    r"""実効設定

ルート設定ファイルと設定インポートを解決し、1回の実行に使用する形へ構成した設定。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_15
