"""Generated vocabulary term references.

Source: ``canonical_documents.vocabulary.canonical``.

Each ``TERM_N`` proxy exposes the human-readable term and definition in
its docstring.  Pass this module to ``@vocabulary(...)`` and use the proxies
with ``vocabulary_refs``.  Canonical vocabulary identity is retained internally.

This file is generated by shikumi-devdoc.  Do not edit it manually.
"""

from __future__ import annotations

import canonical_documents.vocabulary.canonical as _VOCABULARY_SOURCE

_VOCABULARY = _VOCABULARY_SOURCE.VOCABULARY
__shikumi_devdoc_vocabulary_source__ = _VOCABULARY_SOURCE


__all__ = [
    "TERM_1",
    "TERM_2",
    "TERM_3",
    "TERM_4",
    "TERM_5",
    "TERM_6",
    "TERM_7",
    "TERM_8",
    "TERM_9",
    "TERM_10",
    "TERM_11",
    "TERM_12",
    "TERM_13",
    "TERM_14",
    "TERM_15",
    "TERM_16",
    "TERM_17",
    "TERM_18",
    "TERM_19",
]


class TERM_1:
    r"""dirpluck

宣言された抽出意図に従って source から file を選び、ZIP Archive を作成する tool。CLI と最小の Python API を利用入口として持つ。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_1

class TERM_2:
    r"""設定ファイル

dirpluck の抽出意図と、その意図に必要な source、selection、output などを TOML syntax で記述し、`.dirpluck` 拡張子で識別する文書。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_2

class TERM_3:
    r"""対象

実行時にスコープから選ばれ、pluck の selection が適用される source directory。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_3

class TERM_4:
    r"""ケース

同じ source に対して base selection とは別の抽出 variation を表す、名前付きの selection。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_4

class TERM_5:
    r"""常時ソース

Configuration に source directory を固定し、実行のたびに同じ抽出意図へ参加させる source definition。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_5

class TERM_6:
    r"""ソース

1回の実行で file selection の対象となる filesystem directory。対象と常時ソースは、source が実行へ参加する方法の違いを表す。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_6

class TERM_7:
    r"""選択

source から Archive に含める file を、宣言された pattern と policy に従って決めること、またはそのための定義。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_7

class TERM_8:
    r"""アーカイブ

dirpluck が selection result から生成する ZIP artifact。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_8

class TERM_9:
    r"""出力定義

生成する Archive の書き込み先と命名方法を宣言する Configuration definition。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_9

class TERM_10:
    r"""アーカイブREADME

Archive の root に生成され、含まれる source と内容を示す index document。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_10

class TERM_11:
    r"""pluck

今回の実行で選ばれた対象から何を取り出すかを表す selection definition。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_11

class TERM_12:
    r"""共有パターン

複数の selection から名前で参照して再利用する pattern set。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_12

class TERM_13:
    r"""基底設定ファイル

別の Configuration が自身の基礎として参照し、その definition を引き継いで構成する Configuration file。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_13

class TERM_14:
    r"""ルート設定ファイル

1回の dirpluck 実行で CLI から選ばれる最外側の Configuration file。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_14

class TERM_15:
    r"""実効設定

ルート設定ファイルとその base chain を解決し、1回の実行に使用する形へ構成した Configuration。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_15

class TERM_16:
    r"""スコープ

実行時に対象を探す filesystem 上の範囲。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_16

class TERM_17:
    r"""書き込み境界

ひとつの output definition が Archive を書き込める filesystem 上の範囲として、Configuration から静的に定まる境界。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_17

class TERM_18:
    r"""ネームスペース

source を Archive 内で区別して配置するために、source root の外側へ追加する Archive 専用の名前空間。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_18

class TERM_19:
    r"""Invocation Template

Configuration、CLI Target reference、Case などの実行入力を、再利用可能な呼び出しとして保存する `.dirpluck-inv` document。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_19
